In [4]:
import pandas as pd
path = './data/'

In [5]:
sido_all = pd.read_csv(path+'sido_wide.csv', encoding='cp949')

In [6]:
sido_all

,년도,시도,지역,1인가구수,5대범죄 발생건수,가로등수,가스공급설비 면적,가스사고 발생건수,가스사고 부상자수,가스사고 사망자수,...,화재 사망자수,화재 피해액,화재 피해자수,화재구조실적,화재사망자(환산),화재예방교육을 받은 주민 비율,화재피해 경감액,화학물질 및 화학제품 제조업 업체수(의약품제외),화학물질 배출량,황사 발생건수
0,2008,강원도,2008_강원도,NaN,NaN,337.70313,4.83781,NaN,NaN,NaN,...,0.13965,74581.15608,0.69158,3.82363,0.26359,134.03,4.111740e+05,0.71818,47.20130,0.00096
1,2008,경기도,2008_경기도,NaN,NaN,243.18014,26.34827,NaN,NaN,NaN,...,0.06933,63612.79018,0.52043,1.61981,0.14299,13.51,1.176675e+06,2.19787,785.64750,0.00148
2,2008,경상남도,2008_경상남도,NaN,NaN,367.58438,12.35899,NaN,NaN,NaN,...,0.13450,90510.52361,0.59432,6.26534,0.23507,24.58,3.436649e+06,1.74854,836.85569,0.00048
3,2008,경상북도,2008_경상북도,NaN,NaN,348.39731,4.75662,NaN,NaN,NaN,...,0.08205,62247.11005,0.48483,1.82370,0.16653,33.06,6.257514e+05,2.15189,193.17566,0.00053
4,2008,광주광역시,2008_광주광역시,NaN,NaN,254.85269,45.63080,NaN,NaN,NaN,...,0.04952,27235.52543,0.24055,1.81825,0.12391,28.63,1.885752e+06,0.55892,1269.20418,0.01995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2015,전라남도,2015_전라남도,1034.13825,96.18109,NaN,6.98780,NaN,NaN,NaN,...,0.22563,108125.99040,0.91301,3.42117,0.32992,NaN,4.986673e+05,NaN,NaN,0.00333
128,2015,전라북도,2015_전라북도,935.18776,99.41439,NaN,6.78658,NaN,NaN,NaN,...,0.06946,54320.54543,0.37402,2.58608,0.13642,NaN,9.290035e+05,NaN,NaN,0.00211
129,2015,제주특별자치도,2015_제주특별자치도,740.86270,172.06008,NaN,4.71108,NaN,NaN,NaN,...,0.08233,28606.64267,0.51042,6.42138,0.15565,NaN,5.139286e+05,NaN,NaN,0.01460
130,2015,충청남도,2015_충청남도,936.94191,104.31694,NaN,41.88548,NaN,NaN,NaN,...,0.10183,99286.10325,0.41702,1.73595,0.20623,NaN,2.345344e+06,NaN,NaN,0.00292
131,2015,충청북도,2015_충청북도,952.89034,108.76966,NaN,3.13792,NaN,NaN,NaN,...,0.03800,88722.92871,0.48767,3.58470,0.10123,NaN,4.199600e+06,NaN,NaN,0.00108